pipeline{
    agent any
    
    stages{
        stage('Checkout...'){
            steps{
                echo "Checkout code..."
            }
        }
        
        stage('Build'){
            steps{
                echo "Building the code ..."
            }
        }
        
        stage('Deploying'){
            steps{
                echo "Deploying to test env..."
            }
        }
    }
}